# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='待完善', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='待完善', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='待完善', max_length=20, null=True)),
            ],
        ),
    ]
