# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WiSay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
