# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('header_img', models.FileField(upload_to='')),
            ],
        ),
    ]
