# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            managers=[
                ('p_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
