# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            managers=[
                ('userinfo_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
