# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='男', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(default='待完善', max_length=20)),
                ('email', models.CharField(default='待完善', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='女', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(default='待完善', max_length=20)),
                ('email', models.CharField(default='待完善', max_length=20)),
                ('boy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xiaoenai.Boy')),
            ],
        ),
    ]
