# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('xiaoenai', '0002_auto_20171204_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlSay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiaoenai.Girl')),
            ],
            managers=[
                ('gs_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
